stages:
- name: compile
  steps:
  - runScriptConfig:
      image: reg.800best.com/bestapp/bestmvn:3.3.9
      shellScript: mvn clean package
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: test/hello:1.0
      pushRemote: true
      registry: 127.0.0.1:34890
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
branch:
  include:
  - master
notification: {}
