stages:
- name: 编译
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: mvn package
- name: 打包
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: |-
        FROM java:8
        VOLUME /tmp
        ADD /target/*.jar app.jar
        COPY startup.sh /startup.sh
        ENV TZ=Asia/Shanghai
        RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
        RUN bash -c 'touch /app.jar'
        CMD ["sh", "/startup.sh"]
        EXPOSE 8080
timeout: 60
notification: {}
